### ISSUE TITLE
Fails to compile on 2026.1/2026.2

### ISSUE THREAD

**Issue by spitfire** [elupus/esphome-nibe#151]
I'm compiling it with:

 ```
 framework:
    type: arduino
```

It used to fail with esp-idf returning something like `src/esphome/components/nibegw/NibeGw.h:39:10: fatal error: Arduino.h: No such file or directory`, now when I try to switch it it fails wit the same error:

```
Compiling .pioenvs/nibegw/src/esphome/components/safe_mode/button/safe_mode_button.cpp.o
src/esphome/components/nibegw/NibeGwSockAddress.cpp: In member function 'std::string esphome::nibegw::socket_address::str() const':
src/esphome/components/nibegw/NibeGwSockAddress.cpp:66:15: error: 'const struct sockaddr_in6' has no member named 'sin_port'; did you mean 'sin6_port'?
   66 |     if (addr->sin_port != 0) {
      |               ^~~~~~~~
      |               sin6_port
In file included from /cache/platformio/packages/framework-espidf/components/lwip/lwip/src/include/lwip/arch.h:48,
                 from /cache/platformio/packages/framework-espidf/components/lwip/lwip/src/include/lwip/debug.h:40,
                 from /cache/platformio/packages/framework-espidf/components/lwip/lwip/src/include/lwip/opt.h:52,
                 from /cache/platformio/packages/framework-espidf/components/lwip/lwip/src/include/lwip/ip_addr.h:40,
                 from /cache/platformio/packages/framework-arduinoespressif32/cores/esp32/IPAddress.h:25,
                 from /cache/platformio/packages/framework-arduinoespressif32/cores/esp32/Arduino.h:198,
                 from src/esphome/core/macros.h:7,
                 from src/esphome/core/defines.h:2,
                 from src/esphome/components/socket/headers.h:2,
                 from src/esphome/components/socket/socket.h:7,
                 from src/esphome/components/nibegw/NibeGwSockAddress.cpp:7:
src/esphome/components/nibegw/NibeGwSockAddress.cpp:67:47: error: 'const struct sockaddr_in6' has no member named 'sin_port'; did you mean 'sin6_port'?
   67 |       buf += ":" + std::to_string(ntohs(addr->sin_port));
      |                                               ^~~~~~~~
/cache/platformio/packages/framework-espidf/components/lwip/port/esp32xx/include/arch/cc.h:29:36: note: in definition of macro 'ntohs'
   29 | #define ntohs(x) __builtin_bswap16(x)
      |                                    ^
Compiling .pioenvs/nibegw/src/esphome/components/safe_mode/safe_mode.cpp.o
Compiling .pioenvs/nibegw/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/nibegw/src/esphome/components/sensor/filter.cpp.o
*** [.pioenvs/nibegw/src/esphome/components/nibegw/NibeGwSockAddress.cpp.o] Error 1
```

Does it have to do with https://esphome.io/guides/esp32_arduino_to_idf/ ?

**Comment by elupus** [comment]
Hmm. You seem to be enabling IPV6?

**Comment by spitfire** [comment]
> Should be fixed by [#153](https://github.com/elupus/esphome-nibe/pull/153)

Thank you, it worked!


> Hmm. You seem to be enabling IPV6?

No, I have not, at least explicitly.




> I'm not fully following here. But it should compile with esp-idf as framework. So please switch to that.

Sorry if my issue description wa not clear. I'll try to clarify it now.
 I have been trying to compile it using Arduino first, as I had the compile error `src/esphome/components/nibegw/NibeGw.h:39:10: fatal error: Arduino.h: No such file or directory` happen in the past.

When I've tried it at the time I've opened this issue, I've first tried it with Arduino, then ESP-IDF, both were failing with `src/esphome/components/nibegw/NibeGwSockAddress.cpp:67:47: error: 'const struct sockaddr_in6' has no member named 'sin_port'; did you mean 'sin6_port'?`
